# Define a ServiceAccount named kn-deployer-account that has permission to
# manage Knative services.

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kn-deployer-pipeline
rules:
  - apiGroups: ["serving.knative.dev"]
    resources: ["services", "revisions", "routes"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kn-deployer-pipeline-binding
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: workspace-auth-demo
roleRef:
  kind: ClusterRole
  name: kn-deployer-pipeline
  apiGroup: rbac.authorization.k8s.io
